package tadp.parsers

class StringVacioException extends Exception
class CharException extends Exception
class IsDigitException extends Exception
class StringException extends Exception
class ConcatException extends Exception
class RightMostException extends Exception
class ClausuraPositivaException extends Exception
class MapException extends Exception